### ISSUE TITLE
Error in .tiff conversion function in modDownSearch

### ISSUE THREAD

**Issue by sumanjnu** [spatialstatisticsupna/RGISTools#1]
I am getting an error when I try to download the "MOD09GA" band for uttrakhand. .hdf to .tiff conversion function is not working properly
![15815073226658901051595191754880](https://user-images.githubusercontent.com/30377563/74331539-e9802780-4db9-11ea-9b81-44831cb1344b.jpg)

**Comment by unai-perez** [comment]
From the picture, I guess that the main the problem was the download. EarthData we services go under maintenance on wednesdays, which may trigger the file to be empty or corrupted so the translation shows an error. If so, try today and see if that solves the issue. We are working on a way to check the status of the web service in order to avoid this king of issue.
